var num1 = 5;
num1 = num1 + 4;
console.log(num1);
num1++;
console.log(num1);
num1--;
console.log(num1);
console.log(num1/3);
console.log(num1 % 3);
var num2 = 4;
console.log(num1 == num2);
console.log(num1 > num2);
console.log(num1 != num2);
