let color = "rojo \n verde";
console.log(color);
console.log(color.length);
console.log(color.toUpperCase());
let curso = "javascript ";
console.log(curso.includes("t"));
console.log(curso.indexOf("s"));
var wado = curso.repeat(10);
console.log(wado);
var uno = "5";
var dos = "4";
console.log(uno + dos);
console.log(Number(uno)+Number(dos));
document.getElementById("caja").innerHTML = wado;